# Generated by Django 5.0.4 on 2024-05-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0002_alter_plan_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly',
            old_name='monthly_id',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='monthly',
            name='mop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='installment',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmo.monthly'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
