# Generated by Django 5.0.4 on 2024-05-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0004_installment_remove_plan_installment_plan_install_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='install_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='monthly_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentdate',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='modeofpayment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='Monthly',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
