# Generated by Django 5.0.4 on 2024-05-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0005_remove_plan_install_id_remove_plan_monthly_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mop', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='modeofpayment',
        ),
        migrations.AddField(
            model_name='plan',
            name='mop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmo.mop'),
        ),
        migrations.CreateModel(
            name='Up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmo.plan')),
            ],
        ),
    ]
