# Generated by Django 5.0.4 on 2024-05-04 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0006_mop_remove_plan_modeofpayment_plan_mop_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='details',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='downpayment',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='mop',
        ),
        migrations.AddField(
            model_name='payment',
            name='mop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmo.mop'),
        ),
    ]
