# Generated by Django 5.0.4 on 2024-05-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0010_alter_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
