# Generated by Django 5.0.4 on 2024-05-04 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0011_alter_booking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmo.booking'),
        ),
    ]
