# Generated by Django 5.0.4 on 2024-05-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0012_remove_payment_plan_id_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mop',
        ),
        migrations.RemoveField(
            model_name='up',
            name='plan_id',
        ),
        migrations.RemoveField(
            model_name='up',
            name='user_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='mop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='MOP',
        ),
        migrations.DeleteModel(
            name='Up',
        ),
    ]
