# Generated by Django 5.0.4 on 2024-05-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0013_remove_payment_mop_remove_up_plan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='mop',
        ),
        migrations.AddField(
            model_name='booking',
            name='mop',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
