# Generated by Django 5.0.4 on 2024-05-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0016_payment_ref_num_payment_total_boking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymentdate',
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osmo.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
