# Generated by Django 5.0.4 on 2024-05-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0017_rename_amount_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
