# Generated by Django 5.0.4 on 2024-05-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0018_remove_payment_payment_method_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
