# Generated by Django 5.0.4 on 2024-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0022_remove_transaction_amount_transaction_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
