# Generated by Django 5.0.4 on 2024-05-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0026_payment_remaining_balance_payment_total_payable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total_payable',
        ),
    ]
