# Generated by Django 5.0.4 on 2024-05-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0030_booking_amount_booking_ref_num_booking_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
