# Generated by Django 5.0.4 on 2024-05-17 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0034_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmo.booking'),
        ),
    ]
