# Generated by Django 5.0.4 on 2024-05-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0035_todoitem_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='Transaction',
        ),
    ]
