# Generated by Django 5.0.4 on 2024-05-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0036_rename_todoitem_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ref_num',
        ),
    ]
