# Generated by Django 5.0.4 on 2024-05-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0042_transaction_next_payment_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmo.paymentreminder'),
        ),
    ]
