# Generated by Django 5.0.4 on 2024-05-17 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0044_remove_transaction_next_payment_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='next_payment_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='osmo.paymentreminder'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
