# Generated by Django 5.0.4 on 2024-05-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0045_transaction_next_payment_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='next_payment_due',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_reminder',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_payable',
        ),
    ]
