# Generated by Django 5.0.4 on 2024-05-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0047_remove_paymentreminder_user_booking_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreminder',
            name='next_payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
