# Generated by Django 5.0.4 on 2024-05-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0050_paymentreminder_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreminder',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='PaymentPaypal',
        ),
    ]
