# Generated by Django 5.0.4 on 2024-05-18 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0051_remove_paymentreminder_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reminder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmo.paymentreminder'),
        ),
    ]
