# Generated by Django 5.0.4 on 2024-05-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0052_transaction_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreminder',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reminder',
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmo.paymentreminder'),
        ),
    ]
