# Generated by Django 5.0.4 on 2024-05-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0053_remove_paymentreminder_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
