# Generated by Django 5.0.4 on 2024-05-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0054_booking_remaining_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='remaining_balance',
            new_name='balance',
        ),
    ]
