# Generated by Django 5.0.4 on 2024-05-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0055_rename_remaining_balance_booking_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
