# Generated by Django 5.0.4 on 2024-05-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0056_transaction_new_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='new_balance',
        ),
    ]
