# Generated by Django 5.0.4 on 2024-05-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0061_remove_booking_phone_booking_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='account',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
