# Generated by Django 5.0.4 on 2024-05-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0062_remove_account_contact_remove_booking_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
