# Generated by Django 5.0.4 on 2024-05-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0063_account_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
