# Generated by Django 5.0.4 on 2024-05-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmo', '0066_remove_booking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reminder',
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osmo.booking'),
        ),
    ]
